export enum ERootScreenList {
  BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR',
  GUEST_NAVIGATOR = 'GUEST_NAVIGATOR',
  NOTIFICATION = 'NOTIFICATION',
  TRACKMOOD = 'TRACKMOOD',
  MY_PROFILE = 'MY_PROFILE',
  HOMEWORK_DETAIL = 'HOMEWORK_DETAIL',
  DO_ACTIVITY_AND_WRITTEN_TASK = 'DO_ACTIVITY_AND_WRITTEN_TASK',
  DO_QUESTIONNAIRE = 'DO_QUESTIONNAIRE',
  WATCH_VIDEO = 'WATCH_VIDEO',
  HOMEWORK_FEEDBACK = 'HOMEWORK_FEEDBACK',
  HOMEWORK_DONE = 'HOMEWORK_DONE',
  SETTING_NOTIFICATION = 'SETTING_NOTIFICATION',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  PRIVACY = 'PRIVACY',
  TERMS = 'TERMS',
  CONTACT_HELP = 'CONTACT_HELP',
}

export enum EBottomTabScreenList {
  HOME = 'HOME',
  HOMEWORK = 'HOMEWORK',
  PSYCHOEDUCATION = 'PSYCHOEDUCATION',
  MESSAGES = 'MESSAGES',
  SETTING = 'SETTING',
}

export enum EGuestScreenList {
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  VERIFY_OTP = 'VERIFY_OTP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
}

export enum EPsychoEducationList {
  PSYCHOEDUCATION_DETAIL = 'PSYCHOEDUCATION_DETAIL',
  PSYCHOEDUCATION_LIST = 'PSYCHOEDUCATION_LIST',
}
