export enum EClientThunkActions {
  GET_PROFILE = 'GET_PROFILE',
  GET_MOOD_RECENT = 'GET_MOOD_RECENT',
  POST_CLIENT_MOOD = 'POST_CLIENT_MOOD',
  GET_CLIENT_MOOD = 'GET_CLIENT_MOOD',
  UPDATE_INFORMATION = 'GET_PROFILE',
  UPDATE_MEDICAL_PROFILE = 'UPDATE_MEDICAL_PROFILE',
}
